services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: marlonpnc
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registration
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
  pgadmin: